spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # - id: messageService
        #   uri: lb://MESSAGE-SERVICE
        #   predicates:
        #     - Path=/message/**
        #   filters:
        #     - StripPrefix=1
        #     - name: CircuitBreaker
        #       args:
        #         name: messageServiceBreaker
        #     - RewritePath=/test, /testSecour
        - id: cartService
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
        - id: productService
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1