spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cartService
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            # - name: CircuitBreaker
            #   args:
            #     name: cartServiceBreaker
            # - RewritePath=/(.*), /fallback
        - id: productService
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
            # - name: CircuitBreaker
            #   args:
            #     name: productServiceBreaker
            # - RewritePath=/(.*), /fallback